# Generated by Django 5.1.7 on 2025-03-30 15:55

from django.db import migrations, models


def image_upload_to(instance, filename):
    # Legacy function for migration compatibility
    from datetime import datetime
    timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
    lowercase_filename = filename.lower()
    return f"images/{timestamp}_{lowercase_filename}"


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_face_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=image_upload_to)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
