# Generated by Django 5.2.17 on 2026-09-18 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_vault_sessions_otp_biometrics"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="otp_attempts",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="otp_digest",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="otp_expires_at",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="otp_generated",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="otp_secret",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="otp_sent_at",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="otp_session",
        ),
    ]
